

spring:

  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/spring_security
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true



  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://moweja-dev.eu.auth0.com/}
          jwk-set-uri: ${JWT_JWKS_URI:https://moweja-dev.eu.auth0.com/.well-known/jwks.json}


# JWT Configuration
jwt:
  issuer-uri: ${JWT_ISSUER_URI:https://moweja-dev.eu.auth0.com/}
  jwks-uri: ${JWT_JWKS_URI:https://moweja-dev.eu.auth0.com/.well-known/jwks.json}
  audience: ${JWT_AUDIENCE:https://localhost.sh}
  claims-namespace: ${JWT_CLAIMS_NAMESPACE:permissions}  # Optional: for custom claims namespaces







logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: debug

    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.web.filter.OncePerRequestFilter: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource.authentication: TRACE
    com.example.springsecuritydemo: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus

  endpoint:
    health:
      show-details: always