

spring:

  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/spring_security
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true



  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-security
            client-secret: l2qRWguFSr0d8JtjZlgOIsbArvjHuVR4
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - openid
              - profile
              - roles
              - address
            client-name: KeyCloak
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security/protocol/openid-connect/auth
            token-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security/protocol/openid-connect/token
#            user-info-uri: https://keycloak.chaco-climb.ts.net/application/o/userinfo/
            jwk-set-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security/protocol/openid-connect/certs
            issuer-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security
#            user-info-authentication-method: jwt
#            user-name-attribute: preferred_username


      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security/protocol/openid-connect/certs
          issuer-uri: https://keycloak.chaco-climb.ts.net/realms/spring-security
#          authorities-claim-name: roles
#          authority-prefix: ROLE_
#          jws-algorithms: RS256







logging:
  level:
    org:
      springframework:
        security: trace


