name: Java Maven Build
run-name: ${{ github.actor }} is building Java Maven Project 🚀
on:
  - push


jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Repo Checkout
#        run: echo "Checking out repo from ${{ github.repository }} with actions/checkout@v3"
        uses: actions/checkout@v3
      - name: Set up JDK 17
#        run: echo "Setting up JDK 17 with actions/setup-java@v3"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: | 
          echo "mvn clean compile install -DskipTests"
          mvn clean compile install -DskipTests
