name: Java Maven Build
run-name: ${{ github.repository_owner }} is building Java Maven Project 🚀
on:
  - push
  - pull_request


jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Build with Maven
        run: | 
          echo "./mvnw clean compile install -DskipTests"
          ./mvnw clean compile install -DskipTests
  
  

  list-files:
    needs: build
    runs-on: self-hosted
    steps:
      - name: List files
        run: |
          ls target/

  
